language: java
jdk:
- oraclejdk8

# sonar.login
env:
  - secure: dB5bagwpVIxYHzWdRHz56Beh8PBr+vZEMPgFC2lbNfYNYgFg8pCn8DTbO73mqUOJssNoD1hEPf0wysF9btzPP/krF2SakrWtr2ZqeDBMZ8kJBmsnuTq1Z5BSDXh3NBdAtBi1Z4AvPrT9HDJ51TaxovLWmnQ88ki117hADKKXSlK4ZsqoihyfvaPDT11VDUlYz2vDtsee85rnvFkQGostuiJsxGu7PzZZpXwHNl5bJMKaxOG+8ml52rqkybTfKD4tWynJcSSjSxs9lsM5AUbsC7vw3buxCDHdwaZ6rINlmm9rlp4yP5n3HT7FrXDGB9QWALJs6wsZRYpy/zbin1Lw+TFc2DOqHoRWYWs20PlwX1XBoHI4ICUKaVCNPZbWkmXTdb0rYsAzWYghWexcODKqv8W1FaUD5ygsqjJuJccy6KarGqt99IpxQ83V2DmKPPyoB71ZTKB3Vl3kjWUN6sBXNFRAbpKBvLT2EpNb7+QNpFvH2fka0kNS4u4xjJqTeQlVDsH+RMp8m7BtYCI2yLHtZMVwFePZQylQPv/Xx3hM+mWYBI0cIdzVzCDG6x8V4oBSrL/RNmC10Xs6GGwLw8wfEIMgNNy9PjXJmYRsqK1EZllLF98kWZZXuaoc3wxlDfxw1q/9yJSAEDOi/deGhVBRGQjEkLWggYLxH9inC//bJz8=

addons:
  sonarcloud:
    organization: "chutch-github"
    token:
      secure: RRfu0FZtLj9HREU050fq1Di5XTHSjKP8nIErI2uqM5ZLK1z2SkvzxYEHltXhkgLsYUEaOvEFop380/21ijSFODBREZB6Gh5Xnglvv99yXkoazGt6THAV08skcQmZdbnKsiCmd1gK1gFx1dQcuf5Vo0NDyn7w1yufdljU2/9n95ohBCbyT9NGLfWUdMkVEdO6dJH9AttogVZYP1oRI1cq845Lovg7Ss6RFsJTMh/WtM3zIv3wsJZxpdxAT5
        jlQkHyA5sAOW8irorD2PKsrtRV26htgVenttopw2tDUEcWeUPnxncq1WzjxVTpTW12LUFPXyngrnbqjb6PbLVz4Pnyy1kVpE7VjdQIM/FG5h9vT0hSbyCni+p+x3HGucQUjzDLGeMbuto7uPkIoUGnWpIdd140uxI/lzUy+/vf9YA6gWPhXkuEV0PHx0e0/m28/JbQVmJNhVZjsx/JA0OUh/Zo5pFv3U6N88MLdgFvb48q/mQMdzj5WZgm7QuqekTIyMC
        Fng0JHydAYJlnXAOuY2NPwGjUtF2cq57K4MlgD3k/ws5gdI8HIITWgKMcosh1gpws8C4PSxHicqy17beNbIE46zSkYtPhwvHOV8zkL4iYwpn3KP9Ar66oWQy44PaEfI4fVI4IQ1CDoukX0+tyVCE4DNnzqif8/AFO2xB+RWqKkqA=

script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package cobertura:cobertura coveralls:report sonar:sonar